server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_park_db
    username: postgres
    password: aziz0000
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
